In [1]:
import numpy as np

## Array Creation

In [2]:
array_a = np.array([1,2,3,4,5])
print(array_a)

[1 2 3 4 5]


In [5]:
print([1,2,3,4,5])

# This 'normal' Python array can be heterogeneous
# but a NumPy array like the one above is homogeneous (only 1 data type)
# this makes computing faster and more efficient

[1, 2, 3, 4, 5]


In [6]:
print([1,2,3,4,5, 'ulrich'])

[1, 2, 3, 4, 5, 'ulrich']


In [8]:
array_a = np.array([1,2,3,4,5, 'ulrich'])
print(array_a)

# Notice that all the elements have been converted to strings,
# which is not the desired outcome...

['1' '2' '3' '4' '5' 'ulrich']


In [9]:
array_a = np.array([1,2,3,4,5])
print(array_a)

[1 2 3 4 5]


In [11]:
# shape of an array - dimensions
print(array_a.shape)

(5,)


In [13]:
# Multidimensional array
array_b = np.array([[1,2,3,4,5], [1,2,3,4,5]])

print(array_b)
print(array_b.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)


In [14]:
# A 3x3 array
seq_a = [1,2,3]
seq_b = [4,5,6]
seq_c = [7,8,9]

array_abc = np.array([seq_a, seq_b, seq_c])

print(array_abc)
print(array_abc.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


## Indexing & Reshaping

In [17]:
array_a = np.array([[1,2,3],[4,5,6]])

print(array_a.shape)
print(array_a.size)

(2, 3)
6


In [18]:
# To reshape, the size must remain the same
array_b = array_a.reshape(3, 2)
print(array_b)

[[1 2]
 [3 4]
 [5 6]]


In [19]:
# This specific reshape could also be done with a Transpose
array_c = array_a.T
print(array_c)

[[1 4]
 [2 5]
 [3 6]]


In [23]:
# Simple indexing

print(array_b[0])
print(array_b[:,1])
print(array_b[0,0])

[1 2]
[2 4 6]
1


## Default Arrays

In [24]:
# Change the default data type

array_a = np.array([[1,2,3],[4,5,6]], dtype=float)
print(array_a)

[[1. 2. 3.]
 [4. 5. 6.]]


In [26]:
array_b = np.zeros((3,3))
print(array_b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
array_c = np.ones((3,3))
print(array_c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [29]:
array_d = np.full((3,3), 5)
print(array_d)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [30]:
array_e = np.random.random((3,4))
print(array_e)

[[0.38652232 0.09543378 0.62081682 0.08058635]
 [0.26836797 0.80385976 0.08054029 0.20733584]
 [0.57606085 0.14131411 0.78821171 0.21200953]]


## Advanced Indexing

In [31]:
row_1 = [1,2,3,4,5]
row_2 = [6,7,8,9,10]
row_3 = [11,12,13,14,15]
row_4 = [16,17,18,19,20]
row_5 = [21,22,23,24,25]

test_data = np.array([row_1, row_2, row_3, row_4, row_5])
print(test_data)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [34]:
# Slice

print(test_data[:, 2:4:1])

[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]


In [35]:
# Negative indexing

print(test_data[:, -2:-4:-1])

[[ 4  3]
 [ 9  8]
 [14 13]
 [19 18]
 [24 23]]


In [37]:
# Boolean indexing

greater_than_five = test_data > 5
print(greater_than_five)
print(test_data[greater_than_five])

[[False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [41]:
# Conditional ndexing with 'where' method
# Keep the shape of the original array

drop_under_five_array = np.where(test_data > 5, test_data, 0)
print(drop_under_five_array)

[[ 0  0  0  0  0]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [44]:
# Conditional indexing with 'logical_and' method

drop_under_5_and_over_20 = np.logical_and(test_data > 5, test_data < 20)
print(drop_under_5_and_over_20)
print(test_data[drop_under_5_and_over_20])



[[False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True False]
 [False False False False False]]
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19]


## Array Math

In [46]:
array_a = np.array([[1,2],[3,4]])
array_b = np.array([[2,2],[6,6]])

In [55]:
# Single array operations

print(array_a.sum()) # sum all the elements of the array

print(array_a.sum(axis=1)) # sum along the rows

print(array_a.sum(axis=0)) # sum along the columns

print(array_a.cumsum()) # cumulative sum

print(array_a.prod()) # product of all the elements

print(array_a.cumprod()) # cumulative product

10
[3 7]
[4 6]
[ 1  3  6 10]
24
[ 1  2  6 24]


In [57]:
# Two arrays math

print(array_a + array_b) # element by element operations
print(array_a - array_b)
print(array_a * array_b)
print(array_a / array_b)

[[ 3  4]
 [ 9 10]]
[[-1  0]
 [-3 -2]]
[[ 2  4]
 [18 24]]
[[0.5        1.        ]
 [0.5        0.66666667]]


In [58]:
# Vector product of 2 arrays

print(np.dot(array_a, array_b))

[[14 14]
 [30 30]]
