In [2]:
import numpy as np

## Numpy Arrays

In [6]:
my_list =[1,2,3,4]
ar = np.array(my_list)
print(ar)

[1 2 3 4]


In [8]:
mat = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(mat)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
# Numpy arrays using built-in methods

np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
# identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(3)

array([0.66233169, 0.62031694, 0.5783501 ])

In [21]:
np.random.rand(3,3)

array([[0.36162607, 0.27720683, 0.17993086],
       [0.28593104, 0.87339694, 0.94855329],
       [0.17778957, 0.81865355, 0.22302782]])

In [22]:
np.random.randn(4)

array([ 1.06461976,  0.22326239,  0.21779303, -0.34821457])

In [23]:
np.random.randn(4,3)

array([[-0.65412757, -0.41271648,  0.02405072],
       [ 0.37836369,  0.01352743, -0.81467555],
       [ 0.12516169,  1.49727222,  1.48752993],
       [ 1.33922645,  1.50710349,  1.3328661 ]])

In [25]:
np.random.randint(0, 100)

75

In [27]:
ar = np.arange(25)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ar.shape

(25,)

In [29]:
ar.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
arr = np.random.randint(0,100,10)
arr

array([41,  6, 64, 57, 27,  2, 68, 44,  0, 11])

In [35]:
arr.max()

68

In [36]:
arr.min()

0

In [37]:
arr.argmax()

6

In [38]:
arr.argmin()

8

## Indexing & Selection

In [39]:
ar = np.arange(5,20)
ar

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [40]:
ar[4]

9

In [41]:
ar[0:5]

array([5, 6, 7, 8, 9])

In [42]:
ar[4:]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [43]:
ar[:6]

array([ 5,  6,  7,  8,  9, 10])

In [45]:
# Broadcasting
ar[0:4] = 100
ar

array([100, 100, 100, 100,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19])

In [46]:
ar = np.arange(5,20)
ar

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [47]:
slice_ar = ar[0:5]
slice_ar

array([5, 6, 7, 8, 9])

In [48]:
slice_ar[:] = 99
slice_ar

array([99, 99, 99, 99, 99])

In [49]:
ar

array([99, 99, 99, 99, 99, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [50]:
ar_cp = ar.copy()
ar_cp

array([99, 99, 99, 99, 99, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [51]:
ar_cp[:] = 55
ar_cp

array([55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55])

In [52]:
ar

array([99, 99, 99, 99, 99, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [54]:
# Indexing with 2D arrays

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
arr[0][0] # row and column

1

In [57]:
arr[1][1]

5

In [58]:
arr[1,1]

5

In [61]:
# Grab certain sections

arr[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [62]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [63]:
# Conditional selection

ar = np.arange(5,20)
ar

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [64]:
ar[ar<10]

array([5, 6, 7, 8, 9])

In [65]:
ar[ar>15]

array([16, 17, 18, 19])

## Operations

In [66]:
ar = np.arange(0,11)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
ar + ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [68]:
ar * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [69]:
ar + 50

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [70]:
ar/ar

/Users/ulrichmabou/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [71]:
1/ar

/Users/ulrichmabou/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [72]:
ar**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [73]:
# Universal array functions

np.sqrt(ar)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [74]:
np.exp(ar)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [75]:
np.sin(ar)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [76]:
np.log(ar)

/Users/ulrichmabou/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])