In [1]:
import numpy as np
from numpy import random

import pandas as pd
from pandas import Series, DataFrame

## Merging Datasets on Columns

### Many to one merging

In [2]:
dframe1 = DataFrame({'reference': ['ola', 'uber', 'lyft', 'gojek', 'grab'], 'revenue': [1,2,3,4,5]})
dframe2 = DataFrame({'reference': ['ola', 'uber', 'uber', 'ola'], 'revenue': [1,2,3,4]})

print(dframe1)
print(dframe2)

  reference  revenue
0       ola        1
1      uber        2
2      lyft        3
3     gojek        4
4      grab        5
  reference  revenue
0       ola        1
1      uber        2
2      uber        3
3       ola        4


In [3]:
dframe3 = pd.merge(dframe1, dframe2) # index
print(dframe3)

  reference  revenue
0       ola        1
1      uber        2


In [4]:
dframe3 = pd.merge(dframe1, dframe2, on='reference') # reference
print(dframe3)

  reference  revenue_x  revenue_y
0       ola          1          1
1       ola          1          4
2      uber          2          2
3      uber          2          3


In [5]:
dframe4 = pd.merge(dframe1, dframe2, on='reference', how='left') # similar to left outer join in sql?
print(dframe4)

  reference  revenue_x  revenue_y
0       ola          1        1.0
1       ola          1        4.0
2      uber          2        2.0
3      uber          2        3.0
4      lyft          3        NaN
5     gojek          4        NaN
6      grab          5        NaN


In [6]:
dframe5 = pd.merge(dframe1, dframe2, on='reference', how='outer') # similar to full outer join in sql?
print(dframe5)

  reference  revenue_x  revenue_y
0       ola          1        1.0
1       ola          1        4.0
2      uber          2        2.0
3      uber          2        3.0
4      lyft          3        NaN
5     gojek          4        NaN
6      grab          5        NaN


### Many to many merging

In [7]:
dframe6 = DataFrame({'reference': ['ola', 'ola','lyft', 'lyft', 'uber', 'uber', 'ola'], 
                     'revenue': [1,2,3,4,5,6,7]})

dframe7 = DataFrame({'reference': ['uber', 'uber','lyft', 'ola', 'ola'], 
                     'revenue': [1,2,3,4,5]})

print(dframe6)
print(dframe7)




  reference  revenue
0       ola        1
1       ola        2
2      lyft        3
3      lyft        4
4      uber        5
5      uber        6
6       ola        7
  reference  revenue
0      uber        1
1      uber        2
2      lyft        3
3       ola        4
4       ola        5


In [8]:
print(pd.merge(dframe6, dframe7))

  reference  revenue
0      lyft        3


In [9]:
# multiple references

dframe8 = DataFrame({'reference': ['ola', 'ola','lyft'], 
                     'revenue': ['one','two','three'],
                     'profit': [1,2,3]})

dframe9 = DataFrame({'reference': ['ola', 'ola','lyft','lyft'], 
                     'revenue': ['one','one','one','three'],
                     'profit': [4,5,6,7]})

print(pd.merge(dframe8, dframe9, on=['reference','revenue'], how='outer'))


  reference revenue  profit_x  profit_y
0       ola     one       1.0       4.0
1       ola     one       1.0       5.0
2       ola     two       2.0       NaN
3      lyft   three       3.0       7.0
4      lyft     one       NaN       6.0


In [10]:
print(pd.merge(dframe8, dframe9, on=['reference','revenue'], how='outer', suffixes=('_first', '_second')))

  reference revenue  profit_first  profit_second
0       ola     one           1.0            4.0
1       ola     one           1.0            5.0
2       ola     two           2.0            NaN
3      lyft   three           3.0            7.0
4      lyft     one           NaN            6.0


## Merging on indexes - rows

In [11]:
df_1 = DataFrame({'reference': ['O', 'U','L','O','U'], 
                     'data':range(5)})
print(df_1)

df_2 = DataFrame({'profit': [10, 20]}, index = ['O','U'])
print(df_2)

print(pd.merge(df_1, df_2, left_on='reference', right_index=True))

  reference  data
0         O     0
1         U     1
2         L     2
3         O     3
4         U     4
   profit
O      10
U      20
  reference  data  profit
0         O     0      10
3         O     3      10
1         U     1      20
4         U     4      20


In [12]:
df_3 = DataFrame({'ref1':['A','A','O','O','A'], 
                  'ref2': [5,10,15,20,25], 
                  'ref3': np.arange(5.)})
print(df_3)

df_4 = DataFrame({'ref1':['A','A','O','O','O'], 
                  'ref2': [15,20,25,30,35], 
                  'ref3':[2,3,4,5,6]})
print(df_4)

  ref1  ref2  ref3
0    A     5   0.0
1    A    10   1.0
2    O    15   2.0
3    O    20   3.0
4    A    25   4.0
  ref1  ref2  ref3
0    A    15     2
1    A    20     3
2    O    25     4
3    O    30     5
4    O    35     6


In [13]:
# print(pd.merge(df_3, df_4, left_on=['ref1','ref2'], right_index=True)) 

In [14]:
# join functions

print(df_3.join(df_4, lsuffix='x', rsuffix='y'))

  ref1x  ref2x  ref3x ref1y  ref2y  ref3y
0     A      5    0.0     A     15      2
1     A     10    1.0     A     20      3
2     O     15    2.0     O     25      4
3     O     20    3.0     O     30      5
4     A     25    4.0     O     35      6


## Concatenation

In [15]:
A1 = random.randn(25).reshape(5,5)
B1 = np.arange(25).reshape(5,5)

print(A1)
print(B1)

[[-1.28557573  0.69066735 -1.13947156 -2.90391716  0.45627614]
 [ 0.0212049  -0.24086658 -1.13621684  0.73379938  0.43673302]
 [-0.70025799 -1.19836535  0.86551416  0.45712687 -0.54995556]
 [-1.40432006  1.37016342  0.35541927 -0.02030833  1.59206378]
 [ 0.13403064  1.41773868  1.29840541  0.18748752  0.91219775]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [16]:
print(np.concatenate([A1, B1], axis=1)) # Concatenate along the columns

[[-1.28557573e+00  6.90667350e-01 -1.13947156e+00 -2.90391716e+00
   4.56276135e-01  0.00000000e+00  1.00000000e+00  2.00000000e+00
   3.00000000e+00  4.00000000e+00]
 [ 2.12049013e-02 -2.40866583e-01 -1.13621684e+00  7.33799378e-01
   4.36733018e-01  5.00000000e+00  6.00000000e+00  7.00000000e+00
   8.00000000e+00  9.00000000e+00]
 [-7.00257989e-01 -1.19836535e+00  8.65514161e-01  4.57126866e-01
  -5.49955564e-01  1.00000000e+01  1.10000000e+01  1.20000000e+01
   1.30000000e+01  1.40000000e+01]
 [-1.40432006e+00  1.37016342e+00  3.55419265e-01 -2.03083251e-02
   1.59206378e+00  1.50000000e+01  1.60000000e+01  1.70000000e+01
   1.80000000e+01  1.90000000e+01]
 [ 1.34030640e-01  1.41773868e+00  1.29840541e+00  1.87487517e-01
   9.12197750e-01  2.00000000e+01  2.10000000e+01  2.20000000e+01
   2.30000000e+01  2.40000000e+01]]


In [17]:
print(np.concatenate([A1, B1], axis=0)) # Concatenate along rows

[[-1.28557573e+00  6.90667350e-01 -1.13947156e+00 -2.90391716e+00
   4.56276135e-01]
 [ 2.12049013e-02 -2.40866583e-01 -1.13621684e+00  7.33799378e-01
   4.36733018e-01]
 [-7.00257989e-01 -1.19836535e+00  8.65514161e-01  4.57126866e-01
  -5.49955564e-01]
 [-1.40432006e+00  1.37016342e+00  3.55419265e-01 -2.03083251e-02
   1.59206378e+00]
 [ 1.34030640e-01  1.41773868e+00  1.29840541e+00  1.87487517e-01
   9.12197750e-01]
 [ 0.00000000e+00  1.00000000e+00  2.00000000e+00  3.00000000e+00
   4.00000000e+00]
 [ 5.00000000e+00  6.00000000e+00  7.00000000e+00  8.00000000e+00
   9.00000000e+00]
 [ 1.00000000e+01  1.10000000e+01  1.20000000e+01  1.30000000e+01
   1.40000000e+01]
 [ 1.50000000e+01  1.60000000e+01  1.70000000e+01  1.80000000e+01
   1.90000000e+01]
 [ 2.00000000e+01  2.10000000e+01  2.20000000e+01  2.30000000e+01
   2.40000000e+01]]


In [19]:
# Concatenation on series

s1 = Series([100,200,300], index=['A','B','C'])
s2 = Series([400,500], index=['D','E'])

print(s1)
print(s2)

print(pd.concat([s1, s2])) # along the row - axis=0

A    100
B    200
C    300
dtype: int64
D    400
E    500
dtype: int64
A    100
B    200
C    300
D    400
E    500
dtype: int64


In [21]:
print(pd.concat([s1, s2], axis=1, sort=True))

       0      1
A  100.0    NaN
B  200.0    NaN
C  300.0    NaN
D    NaN  400.0
E    NaN  500.0


In [24]:
# Concatenation on dataframes

df1 = DataFrame(random.randn(4,3), columns=['A','B','C'])
df2 = DataFrame(random.randn(3,3), columns=['B','D','A'])

print(df1)
print(df2)

print(pd.concat([df1, df2], sort=True)) 

          A         B         C
0  0.449809 -0.009022 -1.047535
1  0.396444  0.420040 -1.843292
2 -0.045809 -1.073572  0.832906
3 -0.224239 -0.762498 -0.627374
          B         D         A
0 -0.297303 -0.749597  1.550847
1  1.683691  0.570828 -1.203645
2 -0.402549  1.183753 -0.779556
          A         B         C         D
0  0.449809 -0.009022 -1.047535       NaN
1  0.396444  0.420040 -1.843292       NaN
2 -0.045809 -1.073572  0.832906       NaN
3 -0.224239 -0.762498 -0.627374       NaN
0  1.550847 -0.297303       NaN -0.749597
1 -1.203645  1.683691       NaN  0.570828
2 -0.779556 -0.402549       NaN  1.183753


In [25]:
print(pd.concat([df1, df2], ignore_index=True, sort=True)) # continous indexes

          A         B         C         D
0  0.449809 -0.009022 -1.047535       NaN
1  0.396444  0.420040 -1.843292       NaN
2 -0.045809 -1.073572  0.832906       NaN
3 -0.224239 -0.762498 -0.627374       NaN
4  1.550847 -0.297303       NaN -0.749597
5 -1.203645  1.683691       NaN  0.570828
6 -0.779556 -0.402549       NaN  1.183753


## Combine, Stack & Unstack

In [26]:
s1 = Series([5, np.nan, 6, np.nan], index=['A','B','C','D'])
s2 = Series(np.arange(4), dtype=np.float64, index=s1.index)

print(s1)
print(s2)

A    5.0
B    NaN
C    6.0
D    NaN
dtype: float64
A    0.0
B    1.0
C    2.0
D    3.0
dtype: float64


In [31]:
# Replacing the null values of s1 with the corresponding values of s2

s3 = Series(np.where(pd.isnull(s1), s2, s1), 
            index=s1.index)
print(s3)

A    5.0
B    1.0
C    6.0
D    3.0
dtype: float64


In [34]:
# Using the combine function - same as above, but simpler

s4 = s1.combine_first(s2)
print(s4)

A    5.0
B    1.0
C    6.0
D    3.0
dtype: float64


In [35]:
# With dataframes

df_5m = DataFrame({'col1': [5, np.nan, 15], 
                   'col2': [20, 25, np.nan], 
                   'col3': [np.nan, np.nan, 35]})

df_10m = DataFrame({'col1': [0, 10, 20], 
                   'col2': [10, 20, 30]})

print(df_5m)
print(df_10m)

   col1  col2  col3
0   5.0  20.0   NaN
1   NaN  25.0   NaN
2  15.0   NaN  35.0
   col1  col2
0     0    10
1    10    20
2    20    30


In [37]:
print(df_5m.combine_first(df_10m))

   col1  col2  col3
0   5.0  20.0   NaN
1  10.0  25.0   NaN
2  15.0  30.0  35.0


## Reshaping

In [43]:
df1 = DataFrame(np.arange(8).reshape(2,4), index=pd.Index(['Uber','Grab'], name='cabs'), 
                columns=pd.Index(['c1','c2','c3','c4'], name='attributes'))
print(df1)

attributes  c1  c2  c3  c4
cabs                      
Uber         0   1   2   3
Grab         4   5   6   7


In [44]:
# Stacking a dataframe - creating a series from the dataframe

stack_df1 = df1.stack()
print(stack_df1)

cabs  attributes
Uber  c1            0
      c2            1
      c3            2
      c4            3
Grab  c1            4
      c2            5
      c3            6
      c4            7
dtype: int64


In [45]:
# Unstacking

unstack_df1 = stack_df1.unstack()
print(unstack_df1)

attributes  c1  c2  c3  c4
cabs                      
Uber         0   1   2   3
Grab         4   5   6   7


In [41]:
df3 = df1.unstack('cabs')
print(df3)

attributes  cabs
c1          Uber    0
            Grab    4
c2          Uber    1
            Grab    5
c3          Uber    2
            Grab    6
c4          Uber    3
            Grab    7
dtype: int64


In [47]:
# df4 = df1.unstack('attributes')
# print(df4)

In [48]:
# On Series

s1 = Series([5,10,15], index=['A','B','C'])
s2 = Series([15,20,25], index=['B','C','D'])

s3 = pd.concat([s1, s2], keys=['k1','k2'])
print(s3)

k1  A     5
    B    10
    C    15
k2  B    15
    C    20
    D    25
dtype: int64


In [49]:
df5 = s3.unstack()
print(df5)

      A     B     C     D
k1  5.0  10.0  15.0   NaN
k2  NaN  15.0  20.0  25.0


In [50]:
print(df5.stack())

k1  A     5.0
    B    10.0
    C    15.0
k2  B    15.0
    C    20.0
    D    25.0
dtype: float64


In [51]:
print(df5.stack(dropna=False))

k1  A     5.0
    B    10.0
    C    15.0
    D     NaN
k2  A     NaN
    B    15.0
    C    20.0
    D    25.0
dtype: float64


## Pivot Tables

In [52]:
url = "https://en.wikipedia.org/wiki/Pivot_table"
dflist = pd.io.html.read_html(url)
df = dflist[0]
print(df)

  Date of sale Sales person Item sold Color of item  Units sold  \
0     10/01/13        Jones  Notebook         Black           8   
1     10/02/13       Prince    Laptop           Red           4   
2     10/03/13       George     Mouse           Red           6   
3     10/04/13        Larry  Notebook         White          10   
4     10/05/13        Jones     Mouse         Black           4   

   Per unit price  Total price  
0           25000       200000  
1           35000       140000  
2             850         5100  
3           27000       270000  
4             700         2800  


In [53]:
# pivot table

print(df.pivot('Date of sale', 'Sales person', 'Total price'))

Sales person  George     Jones     Larry    Prince
Date of sale                                      
10/01/13         NaN  200000.0       NaN       NaN
10/02/13         NaN       NaN       NaN  140000.0
10/03/13      5100.0       NaN       NaN       NaN
10/04/13         NaN       NaN  270000.0       NaN
10/05/13         NaN    2800.0       NaN       NaN


## Dealing with Duplicates

In [59]:
df = DataFrame({'col1': ['uber','uber','uber','grab','grab'], 
                'col2': [5,4,3,3,5]})
print(df)

   col1  col2
0  uber     5
1  uber     4
2  uber     3
3  grab     3
4  grab     5


In [60]:
# Finding the duplicates

print(df.duplicated())

0    False
1    False
2    False
3    False
4    False
dtype: bool


In [62]:
df2 = DataFrame({'col1': ['uber','uber','uber','uber','grab'], 
                'col2': [5,4,3,3,5]})
print(df2)

print(df2.duplicated())

   col1  col2
0  uber     5
1  uber     4
2  uber     3
3  uber     3
4  grab     5
0    False
1    False
2    False
3     True
4    False
dtype: bool


In [63]:
# Dropping the duplicates

print(df2.drop_duplicates())

   col1  col2
0  uber     5
1  uber     4
2  uber     3
4  grab     5


In [64]:
# Dropping duplicates in columns

print(df2.drop_duplicates(['col1']))

   col1  col2
0  uber     5
4  grab     5


In [67]:
# Keeping the last last value among the duplicates

print(df2.drop_duplicates(['col1'], keep='last'))

   col1  col2
3  uber     3
4  grab     5


## Mapping in a Dataframe

In [68]:
df = DataFrame({'country': ['Afghanistan','Albania','Algeria'],
               'code': ['93','355','213']})
print(df)

       country code
0  Afghanistan   93
1      Albania  355
2      Algeria  213


In [69]:
GDP_map = {'Afghanistan': '20', 'Albania': '12.8', 'Algeria': '215'}
print(GDP_map)

{'Afghanistan': '20', 'Albania': '12.8', 'Algeria': '215'}


In [71]:
df['GDP'] = df['country'].map(GDP_map)
print(df)

       country code   GDP
0  Afghanistan   93    20
1      Albania  355  12.8
2      Algeria  213   215


## Replacing values in series

In [74]:
s1 = Series([10,20,40,50,20,10,50,40])
print(s1)

0    10
1    20
2    40
3    50
4    20
5    10
6    50
7    40
dtype: int64


In [76]:
print(s1.replace(50, np.nan)) # replacing 50 with null values

0    10.0
1    20.0
2    40.0
3     NaN
4    20.0
5    10.0
6     NaN
7    40.0
dtype: float64


In [77]:
print(s1.replace([10,20,50], [100,200,500])) # replacing multiple values

0    100
1    200
2     40
3    500
4    200
5    100
6    500
7     40
dtype: int64


In [78]:
print(s1.replace({10:100, 20:np.nan, 40:400})) # replacing values with a dictionary

0    100.0
1      NaN
2    400.0
3     50.0
4      NaN
5    100.0
6     50.0
7    400.0
dtype: float64


## Renaming Indexes

In [79]:
df = DataFrame(np.arange(25).reshape(5,5), 
               index=['UBER','OLA','GRAB','GOJEK','LYFT'], 
               columns=['RE','LO','QU','GR','AG'])
print(df)

       RE  LO  QU  GR  AG
UBER    0   1   2   3   4
OLA     5   6   7   8   9
GRAB   10  11  12  13  14
GOJEK  15  16  17  18  19
LYFT   20  21  22  23  24


In [81]:
# Using mapping to rename indexes

df.index = df.index.map(str.lower) # indexes to lowercase
print(df)

       RE  LO  QU  GR  AG
uber    0   1   2   3   4
ola     5   6   7   8   9
grab   10  11  12  13  14
gojek  15  16  17  18  19
lyft   20  21  22  23  24


In [84]:
# Using the rename method to rename indexes

print(df.rename(index=str.title, columns=str.lower))


       re  lo  qu  gr  ag
Uber    0   1   2   3   4
Ola     5   6   7   8   9
Grab   10  11  12  13  14
Gojek  15  16  17  18  19
Lyft   20  21  22  23  24


In [86]:
# Using a dictionary to change indexes

print(df.rename(index={'uber':'The best'}, columns={'RE':'Revenue'}))

          Revenue  LO  QU  GR  AG
The best        0   1   2   3   4
ola             5   6   7   8   9
grab           10  11  12  13  14
gojek          15  16  17  18  19
lyft           20  21  22  23  24


In [87]:
# Renaming and saving in memory

df.rename(index={'uber':'The best'}, columns={'RE':'Revenue'}, inplace=True)
print(df)

          Revenue  LO  QU  GR  AG
The best        0   1   2   3   4
ola             5   6   7   8   9
grab           10  11  12  13  14
gojek          15  16  17  18  19
lyft           20  21  22  23  24


## Binning Values

In [88]:
prime_numbers = [2,3,5,7,11,13,17,19,23,29,31,37,41,43,47]

number_bins = [0,10,20,30,40,50]

category = pd.cut(prime_numbers, number_bins)

print(category)

[(0, 10], (0, 10], (0, 10], (0, 10], (10, 20], ..., (30, 40], (30, 40], (40, 50], (40, 50], (40, 50]]
Length: 15
Categories (5, interval[int64]): [(0, 10] < (10, 20] < (20, 30] < (30, 40] < (40, 50]]


In [89]:
print(category.categories)

IntervalIndex([(0, 10], (10, 20], (20, 30], (30, 40], (40, 50]],
              closed='right',
              dtype='interval[int64]')


In [90]:
print(pd.value_counts(category))

(10, 20]    4
(0, 10]     4
(40, 50]    3
(30, 40]    2
(20, 30]    2
dtype: int64


In [91]:
print(pd.cut(prime_numbers, 3, precision=1))

[(2.0, 17.0], (2.0, 17.0], (2.0, 17.0], (2.0, 17.0], (2.0, 17.0], ..., (17.0, 32.0], (32.0, 47.0], (32.0, 47.0], (32.0, 47.0], (32.0, 47.0]]
Length: 15
Categories (3, interval[float64]): [(2.0, 17.0] < (17.0, 32.0] < (32.0, 47.0]]


## Observations on Dataframes

In [93]:
df = DataFrame(np.random.randn(1000,5))
print(df)

            0         1         2         3         4
0    0.016981  0.507002 -0.007224 -0.124253  1.019130
1    0.921940  2.584330 -0.150516 -1.066901  1.543648
2   -0.607158  1.192339 -0.074251 -0.196025  1.547812
3    0.361329  0.857075  1.091804 -0.583308 -0.793331
4    0.760247  0.635524 -0.629203 -0.668640  0.852296
..        ...       ...       ...       ...       ...
995  1.992026 -0.677164  0.359728 -1.440335 -1.174272
996  0.820284  1.107816  0.327750  0.381373 -0.738217
997 -1.281891 -0.007687  0.348703  0.538619 -0.924867
998 -0.623547 -0.012786 -0.503785 -2.120179  1.053466
999 -1.294600  0.149326  0.271470 -0.696224 -0.417560

[1000 rows x 5 columns]


In [94]:
df.head()

0         1         2         3         4
0  0.016981  0.507002 -0.007224 -0.124253  1.019130
1  0.921940  2.584330 -0.150516 -1.066901  1.543648
2 -0.607158  1.192339 -0.074251 -0.196025  1.547812
3  0.361329  0.857075  1.091804 -0.583308 -0.793331
4  0.760247  0.635524 -0.629203 -0.668640  0.852296

In [95]:
df.tail()

0         1         2         3         4
995  1.992026 -0.677164  0.359728 -1.440335 -1.174272
996  0.820284  1.107816  0.327750  0.381373 -0.738217
997 -1.281891 -0.007687  0.348703  0.538619 -0.924867
998 -0.623547 -0.012786 -0.503785 -2.120179  1.053466
999 -1.294600  0.149326  0.271470 -0.696224 -0.417560

In [96]:
df.describe()

0            1            2            3            4
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.025872     0.042529     0.021257     0.000165     0.010334
std       0.995587     1.021335     1.007767     1.009801     0.986622
min      -3.767240    -3.626928    -3.840668    -2.958843    -3.148342
25%      -0.652374    -0.648601    -0.675101    -0.698783    -0.683833
50%      -0.011248     0.017820     0.042713    -0.003307    -0.021333
75%       0.641616     0.706591     0.730585     0.663425     0.700501
max       3.002745     3.035073     3.035147     3.454859     3.213092

In [97]:
column = df[0]
column.head()

0    0.016981
1    0.921940
2   -0.607158
3    0.361329
4    0.760247
Name: 0, dtype: float64

In [99]:
column[np.abs(column)>3] # only return the elements of the column with an absolute value greater than 3

450   -3.097647
580    3.002745
665   -3.052788
694   -3.177054
877   -3.767240
Name: 0, dtype: float64

In [101]:
# return all the rows of the dataframe where at least 1 element has an absolute value greater than 3
df[(np.abs(df)>3).any(1)] 

0         1         2         3         4
36   0.999154 -0.255100 -0.795448  3.084903  1.075723
99  -0.319735 -0.514322  1.341787  3.454859  0.236459
149  0.195969 -1.634706  0.550443  0.632452 -3.019441
238  1.271800  0.215127 -0.266239  3.100657  0.114898
450 -3.097647 -2.302262 -0.987600  0.525611 -1.140636
497  1.387693  0.424668 -0.153097 -0.101404 -3.148342
531  0.181724 -3.626928 -0.739751  1.334598  0.194981
580  3.002745 -0.270272 -1.736167  0.432572 -0.502366
665 -3.052788  1.260302  0.270334 -0.767722  0.019066
667 -2.047453  0.855645 -0.233430  0.071285  3.213092
694 -3.177054 -0.777920  0.454123 -0.251193  0.574748
695  0.487272 -0.533004 -3.840668 -0.363238  0.385782
723  1.149568  3.035073  0.560006 -0.365288  1.274071
859  1.038773 -3.130095 -0.353724  0.859275 -0.228161
877 -3.767240 -0.338669 -0.873236 -0.773204  0.282111
878 -1.928072  1.680427  3.035147  0.391580 -1.259983
880  0.451108  0.546453 -3.630070 -1.840954 -1.299969